build-icarus-arm64v8-opencv-4.4.0-cuda102:
	sudo docker build -f dockerfile.opencv.cuda102 -t prominendt/icarus-arm64v8-opencv-4.4.0:cuda102 .

push-icarus-arm64v8-opencv-4.4.0-cuda102:
	sudo docker push prominendt/icarus-arm64v8-opencv-4.4.0:cuda102
