build-icarus-arm64v8-opencv-4.4.0_basic:
	sudo docker build -f dockerfile.opencv.basic -t prominendt/icarus-arm64v8-opencv-4.4.0:basic .

build-icarus-arm64v8-opencv-4.4.0_cuda102a53:
	sudo docker build -f dockerfile.opencv.cuda102a53 -t prominendt/icarus-arm64v8-opencv-4.4.0:cuda102a53 .

build-icarus-arm64v8-opencv-4.4.0_cuda102a72:
	sudo docker build -f dockerfile.opencv.cuda102a72 -t prominendt/icarus-arm64v8-opencv-4.4.0:cuda102a72 .

push-icarus-arm64v8-opencv-4.4.0_basic:
	sudo docker push prominendt/icarus-arm64v8-opencv-4.4.0:basic

push-icarus-arm64v8-opencv-4.4.0_cuda102a53:
	sudo docker push prominendt/icarus-arm64v8-opencv-4.4.0:cuda102a53

push-icarus-arm64v8-opencv-4.4.0_cuda102a72:
	sudo docker push prominendt/icarus-arm64v8-opencv-4.4.0:cuda102a72
