build-icarus_arm64v8-cuda102a53-py3.7-opencv4.4.0:
	sudo docker build -f dockerfile.arm64v8-cuda102a53-py3.7-opencv4.4.0 -t prominendt/icarus:arm64v8-cuda102a53-py3.7-opencv4.4.0 .

push-icarus_arm64v8-cuda102a53-py3.7-opencv4.4.0:
	sudo docker push prominendt/icarus:arm64v8-cuda102a53-py3.7-opencv4.4.0

build-icarus_amd64-py3.7-opencv4.4.0:
	sudo docker build -f dockerfile.amd64-py3.7-opencv4.4.0 -t prominendt/icarus:amd64-py3.7-opencv4.4.0 .

push-icarus_amd64-py3.7-opencv4.4.0:
	sudo docker push prominendt/icarus:amd64-py3.7-opencv4.4.0