build-icarus_arm64v8-cuda102a53-py3.6-opencv4.4.0-tf2.7:
	sudo docker build -f dockerfile.arm64v8-cuda102a53-py3.6-opencv4.4.0-tf2.7 -t prominendt/icarus:arm64v8-cuda102a53-py3.6-opencv4.4.0-tf2.7 .

push-icarus_arm64v8-cuda102a53-py3.6-opencv4.4.0-tf2.7:
	sudo docker push prominendt/icarus:arm64v8-cuda102a53-py3.6-opencv4.4.0-tf2.7