build-icarus-arm64v8-opencv-4.4.0:
	sudo docker build -f dockerfile.opencv.basic -t prominendt/icarus-arm64v8-opencv-4.4.0:basic .

push-icarus-arm64v8-opencv-4.4.0:
	sudo docker push prominendt/icarus-arm64v8-opencv-4.4.0:basic
