build-icarus-arm64v8-opencv-4.4.0:
	sudo docker build -f dockerfile.opencv.basic -t prominendt/icarus-arm64v8-opencv-4.4.0:basic .

build-icarus-arm64v8-opencv-4.4.0_u2004:
	sudo docker build -f dockerfile.opencv.basic_u2004 -t prominendt/icarus-arm64v8-opencv-4.4.0:basic_u2004 .

push-icarus-arm64v8-opencv-4.4.0:
	sudo docker push prominendt/icarus-arm64v8-opencv-4.4.0:basic
